### ISSUE TITLE
Contract check failed

### ISSUE THREAD

**Issue by SleepingPanda** [gmbeard/shadow-cast#36] opened 2024-07-21 14:21 UTC
Sorry to open so many issues in such a short space of time. I've tried executing shadow-cast but get this error:
```
$ shadow-cast Videos/Test.mkv
[hevc_nvenc @ 0x22c30280] ignoring invalid SAR: 0/0
capturing rate: 48000, channels: 2
Finalizing output. Please wait...
Contract check failed: pid_ == -1 - /home/SleepingPanda/shadow-cast/src/io/process.cpp:27
terminate called without an active exception
Aborted (core dumped)
```
As in the previous issue, I'm on Fedora 40 but also with the latest nvidia proprietary driver. Here's the output of `nvidia-smi`, `uname -a` and `cat /etc/os-release`:

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.58.02              Driver Version: 555.58.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1080        Off |   00000000:01:00.0  On |                  N/A |
|  0%   56C    P8             12W /  240W |     790MiB /   8192MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

```

```
$ uname -a
Linux VENUS 6.9.9-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 11 19:29:01 UTC 2024 x86_64 GNU/Linux
```

```
$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="40 (KDE Plasma)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (KDE Plasma)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="KDE Plasma"
VARIANT_ID=kde
```

**Comment by gmbeard** [comment] 2024-07-21 15:36
I'll have to try and reproduce this error myself. I've only tested the Wayland back-end with Gnome and Sway so far, and maybe this is a KDE specific issue.

If you up to helping diagnose this, then applying the following patch may uncover some more detail about the error...

```diff
diff --git a/src/io/process.cpp b/src/io/process.cpp
index b42616c..bfceef7 100644
--- a/src/io/process.cpp
+++ b/src/io/process.cpp
@@ -24,7 +24,7 @@ Process::Process(Process&& other) noexcept
 {
 }
 
-Process::~Process() { SC_EXPECT(pid_ == -1); }
+Process::~Process() {}
 
 auto Process::operator=(Process&& other) noexcept -> Process&
 {
```

No worries if not, though. You've been patient enough :smile:

**Comment by gmbeard** [comment] 2024-07-21 16:20
Could you paste the output of the following commands...

```sh
$ command -v shadow-cast-kms
$ which shadow-cast-kms
```

**Comment by gmbeard** [comment] 2024-07-21 18:17
Could you also provide the output of...

```sh
$ getcap /usr/local/bin/shadow-cast-kms
```

**Comment by gmbeard** [comment] 2024-07-21 20:41
Thank you. Everything looks to be installed correctly, so there must be a bug in the Wayland frame capture.

This patch will enable some extra logging to STDERR. It may give some indication where the failure is...

```diff
diff --git a/src/kms.cpp b/src/kms.cpp
index bc20e24..ff09a7b 100644
--- a/src/kms.cpp
+++ b/src/kms.cpp
@@ -24,7 +24,7 @@
 using IncomingMessage = sc::DRMRequest;
 using OutgoingMessage = sc::DRMResponse;
 
-auto constexpr kEnableLogging = false;
+auto constexpr kEnableLogging = true;
 
 struct NullLogger
 {
```

(The logging can be quite extensive with this enabled, hence why it's normally disabled)

**Comment by gmbeard** [comment] 2024-07-21 21:05
No, that's fine. It's showing exactly where the problem lies - it's claiming that there isn't a DRM kernel driver loaded.

That's seems odd as it was my understanding that a DRM driver is a prerequisite for running Wayland!

Do you know if you're booting your kernel with the following setting - `nvidia_drm.modeset=1`

**Comment by gmbeard** [comment] 2024-07-21 21:55
I shall have to do some further digging. It may be that a later nvidia driver has changed this behaviour. Appreciate the help with debugging :+1:

**Comment by gmbeard** [comment] 2024-07-22 20:11
@SleepingPanda I'm still struggling to reproduce the `ERROR: DRM not available` issue. Is there any chance you may be able to try this patch at some point?

```patch
diff --git a/src/kms.cpp b/src/kms.cpp
index bc20e24..58c8e1e 100644
--- a/src/kms.cpp
+++ b/src/kms.cpp
@@ -52,7 +52,7 @@ decltype(auto) log()
     }
 }
 
-[[nodiscard]] auto is_drm_available() -> bool { return drmAvailable() == 1; }
+[[nodiscard]] auto is_drm_available() -> bool { return true; }
 
 [[nodiscard]] auto get_drm_device_path() -> std::string
 {
```

I'm wondering if the DRM driver check is reporting a false negative, so this patch will force the DRM check to pass

**Comment by gmbeard** [comment] 2024-07-22 22:26
Aha, that looks promising. Does your output file have content?

**Comment by gmbeard** [comment] 2024-07-23 07:04
Thanks. Ok, that looks like a "10bit" pixel format. Do you have HDR enabled by any chance. If so, are you able to switch to non HDR temporarily to see if that has any effect?

**Comment by gmbeard** [comment] 2024-07-23 07:18
Potentially, yeah. Shadow Cast naively only supports 8bit per pixel formats on Wayland, currently. The colorspace / color conversion needs a bit of TLC

**Comment by gmbeard** [comment] 2024-07-23 07:43
I found this post about KDE's default color depth - https://discuss.kde.org/t/kde-wayland-view-set-color-bit-depth/2019/2

It suggests that KDE defaults to 10 bit-per-pixel color if it's supported (which is what appears to be happening in our case), and you can change it by adding this to `/etc/environment`

```
KWIN_DRM_PREFER_COLOR_DEPTH=24
```

I can't vouch for this, though, so it's up to you if you're comfortable trying it or not. Idealy, I need to fix this in Shadow Cast itself

**Comment by gmbeard** [comment] 2024-07-23 17:06
Ah, looks like that env var had no effect. Worth a try!

No problem. I'm going to spend some time implementing proper color conversion for Wayland - I've been putting it off long enough at this point, really! 

Really appreciate your help with debugging these issues. You've been more than helpful. Nice work :smile: 

I'll probably open some new GitHub issues to track some of the problems we've faced here - They can be useful for posterity if others have similar issues

**Comment by gmbeard** [comment] 2024-07-29 21:13
Hi @SleepingPanda,

I've done a first pass of the color conversion. I' haven't yet managed to get KDE plasma running to test it myself, but feel free to try it yourself if you wish - it's on the [`feat/drm-color-conversion`](https://github.com/gmbeard/shadow-cast/tree/fix/drm-color-conversion) branch.

**Comment by gmbeard** [comment] 2024-07-30 18:48
No problem. Thank you.

BTW, I'm now tracking this issue here: https://github.com/gmbeard/shadow-cast/issues/39, so I will close this one

**Closed** 2024-07-30 18:48 UTC
Labels: needs testing
